attention_head_size: 4
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: true
  add_target_scales: true
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        nyiso: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U5
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 20
          - 4
          - 8
        - false
        - !!binary |
          bgAAAHkAAABpAAAAcwAAAG8AAAA=
      warn: true
    group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_: &id006
        nyiso: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U5
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 20
          - 4
          - 8
        - false
        - !!binary |
          bgAAAHkAAABpAAAAcwAAAG8AAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group
  lags: null
  max_encoder_length: 336
  max_prediction_length: 24
  min_encoder_length: 336
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - &id005 !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    3Y0GAAAAAAA=
  min_prediction_length: 24
  predict_mode: false
  randomize_length: null
  scalers:
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    extreme_flag: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - extreme_flag
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          OOvsPyfatT8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          Uq7ic/bh0T8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          liiR6KL8sz8=
      with_mean: true
      with_std: true
    holiday: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - holiday
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          h8xKq8VloT8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          PM6hwsswxz8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          5u8hUG/OoD8=
      with_mean: true
      with_std: true
    relative_time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - relative_time_idx
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    temp: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - temp
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          aECZ1xBRKUA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          Mbh8nvFEI0A=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          IRZs7OY0V0A=
      with_mean: true
      with_std: true
    y_center: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - y_center
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          iFioTeTi0EA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    y_scale: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.8.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - - y_scale
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          Tqig0u20qEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAOBh5UA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
  static_categoricals:
  - group
  static_reals: null
  target: y
  target_normalizer: &id007 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups:
    - group
    _method_kwargs: {}
    center: true
    groups:
    - group
    method: standard
    method_kwargs: {}
    missing_:
      center: 17291.567239843804
      scale: 3162.4644975858155
    norm_: !!python/object:pandas.core.frame.DataFrame
      _flags:
        allows_duplicate_labels: true
      _metadata: []
      _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
      - !!python/tuple
        - !!python/object/apply:pandas._libs.internals._unpickle_block
          - !!python/object/apply:numpy._core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
              - 1
            - *id002
            - false
            - !!binary |
              iFioTeTi0EBMqKDS7bSoQA==
          - !!python/object/apply:builtins.slice
            - 0
            - 2
            - 1
          - 2
      - - !!python/object/apply:pandas.core.indexes.base._new_Index
          - &id004 !!python/name:pandas.core.indexes.base.Index ''
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 2
              - *id003
              - false
              - - center
                - scale
            name: null
        - !!python/object/apply:pandas.core.indexes.base._new_Index
          - *id004
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 1
              - *id005
              - false
              - !!binary |
                AAAAAAAAAAA=
            name: group
      _typ: dataframe
      attrs: {}
    scale_by_group: false
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - holiday
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - y
  - temp
  - extreme_flag
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels:
  group: *id006
embedding_paddings: []
embedding_sizes:
  group: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 96
learning_rate: 0.001
log_gradient_flow: false
log_interval: 50
log_val_interval: null
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 336
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 3
output_transformer: *id007
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 3
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- group
static_reals:
- encoder_length
- y_center
- y_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- holiday
- relative_time_idx
time_varying_reals_encoder:
- holiday
- relative_time_idx
- y
- temp
- extreme_flag
weight_decay: 0.0
x_categoricals:
- group
x_reals:
- encoder_length
- y_center
- y_scale
- holiday
- relative_time_idx
- y
- temp
- extreme_flag
